#!/bin/bash
# ---------------------------------------------------------------------
# COMPILERS COURSE - SCRIPT                                           -
# SCRIPT A12 - CST8152 - Fall 2023                                    -
# ---------------------------------------------------------------------

clear
COMPILER=./Compiler

FILE1=INPUT0_Empty
FILE2=INPUT1_Hello
FILE3=INPUT2_Volume
FILE4=INPUT3_Factorial
FILE5=INPUT4_Datatypes
FILE6=INPUT5_General
FILE7=INPUT6_Big

ASSIGNMENT=A12
EXTENSION=mx
OUTPUT=out
ERROR=err

PARAM=r

# ---------------------------------------------------------------------
# Begin of Tests (A12 - F23) ------------------------------------------
# ---------------------------------------------------------------------
echo "[READER SCRIPT .........................]"
echo ""

mv *.exe $COMPILER

#
# BASIC TESTS  ----------------------------------------------------------
#
# Basic Tests (A12 - F23) - - - - - - - - - - - - - - - - - - - - - -

mkdir output 2> /dev/null

$COMPILER $PARAM $FILE1.$EXTENSION	> output/$FILE1-$ASSIGNMENT.$OUTPUT	2> output/$FILE1-$ASSIGNMENT.$ERROR
$COMPILER $PARAM $FILE2.$EXTENSION	> output/$FILE2-$ASSIGNMENT.$OUTPUT	2> output/$FILE2-$ASSIGNMENT.$ERROR
$COMPILER $PARAM $FILE3.$EXTENSION	> output/$FILE3-$ASSIGNMENT.$OUTPUT	2> output/$FILE3-$ASSIGNMENT.$ERROR
$COMPILER $PARAM $FILE4.$EXTENSION	> output/$FILE4-$ASSIGNMENT.$OUTPUT	2> output/$FILE4-$ASSIGNMENT.$ERROR
$COMPILER $PARAM $FILE5.$EXTENSION	> output/$FILE5-$ASSIGNMENT.$OUTPUT	2> output/$FILE5-$ASSIGNMENT.$ERROR
$COMPILER $PARAM $FILE6.$EXTENSION	> output/$FILE6-$ASSIGNMENT.$OUTPUT	2> output/$FILE6-$ASSIGNMENT.$ERROR

#
# ADVANCED TESTS  -------------------------------------------------------
#
# Advanced Tests (A12 - F23) - - - - - - - - -- - - - - - - - - - - -

$COMPILER $PARAM $FILE7.$EXTENSION	f 100 10	> output/$FILE7-$ASSIGNMENT-f-100-10.$OUTPUT	2> output/$FILE7-$ASSIGNMENT-f-100-10.$ERROR
$COMPILER $PARAM $FILE7.$EXTENSION	a 100 10	> output/$FILE7-$ASSIGNMENT-a-100-10.$OUTPUT	2> output/$FILE7-$ASSIGNMENT-a-100-10.$ERROR
$COMPILER $PARAM $FILE7.$EXTENSION	m 100 10	> output/$FILE7-$ASSIGNMENT-m-100-10.$OUTPUT	2> output/$FILE7-$ASSIGNMENT-m-100-10.$ERROR

# SHOW OUTPUTS - - - - - - - - - - - - - - - - - - - - - - - - - - -

cat output/*.out
cat output/*.err

# ---------------------------------------------------------------------
# End of Tests (A12 - F23) --------------------------------------------
# ---------------------------------------------------------------------
